In [8]:
import pandas as pd
import os
import shutil

In [9]:
df = pd.read_csv("CycPepDB.csv")
df["Date"] = pd.to_datetime(df["Date"])
df["PDB"] = df["PDB"].apply(lambda x: x.lower())
df["Pep_lengths"] = df["Pep_lengths"].apply(lambda x: x.split(";")[-1].split(":")[-1])
total_structs = len(df)


complexes_df = df.dropna(subset=["Prot_chains", "Link", "Resolution"])
complexes_df = complexes_df[((complexes_df["Method"] == "X-ray") | (complexes_df["Method"] == "NMR")) & (24 >= complexes_df["Pep_lengths"].astype("int32"))]

complexes_df

,PDB,Method,Resolution,Date,SSBond,Link,Pep_chains,Prot_chains,Pep_lengths,Prot_lengths,Note,Format
3,1vs2,X-ray,2.0,1986-10-21,B3-B7,B1-B8,B,A,8,A:8,UAA,pdb
4,1vtg,X-ray,1.67,1988-08-18,B3-B7,B1-B8,B,A,8,A:6,UAA,pdb
76,2rmc,X-ray,1.64,1994-01-07,NaN,B1-B11;D1-D11;F1-F11;H1-H11,BDFH,ACEG,11,A:182;C:182;E:182;G:182,UAA,pdb
77,2rmb,X-ray,2.1,1994-01-07,NaN,B1-B11;D1-D11;F1-F11;H1-H11;J1-J11;L1-L11;N1-N...,BDFHJLNPRT,ACEGIKMOQS,11,A:165;C:165;E:165;G:165;I:165;K:165;M:165;O:16...,UAA,pdb
78,2rma,X-ray,2.1,1994-01-07,NaN,B1-B11;D1-D11;F1-F11;H1-H11;J1-J11;L1-L11;N1-N...,BDFHJLNPRT,ACEGIKMOQS,11,A:165;C:165;E:165;G:165;I:165;K:165;M:165;O:16...,UAA,pdb
...,...,...,...,...,...,...,...,...,...,...,...,...
3034,8vx7,X-ray,2.75,2024-02-03,NaN,C1-C8,C,AB,8,A:162;B:162,UAA,pdb
3042,8ys7,X-ray,3.24,2024-03-22,E3-E7;A3-A7,E1-E8;A1-A8,AE,BCDIKL,8,B:8;C:7;D:11;I:11;K:8;L:7,UAA,pdb
3060,8zeb,X-ray,1.95,2024-05-05,NaN,D1-D15;C1-C15,CD,AB,15,A:141;B:141,UAA,pdb
3075,9cdz,X-ray,1.72,2024-06-25,NaN,B1-B16;D1-D16,BD,AC,16,A:108;C:108,UAA,pdb
3091,9din,X-ray,1.64,2024-09-05,NaN,C1-C7,C,A,7,A:158,UAA,mmCIF

In [10]:
complexes_df.to_csv("filtered_complexes.csv", index=0)

In [19]:
for name in complexes_df["PDB"].to_list():
    cif = os.path.join("cpdb_all_cifs", f"{name}.cif.gz")
    shutil.copy(cif, "complexes")

In [20]:
#Clustering

In [21]:
clustered_df = pd.read_csv("clu_cluster.tsv", sep="\t", names=["cluster_rep", "PDB"])
clustered_df

    cluster_rep   PDB
0          1c5f  1c5f
1          1fjm  1fjm
2          1h0g  1h0g
3          1h0i  1h0i
4          1m63  1m63
..          ...   ...
223        8xp8  8xp8
224        8xpb  8xpb
225        8ys7  8ys7
226        8zeb  8zeb
227        9cdz  9cdz

[228 rows x 2 columns]

In [24]:
counts = clustered_df.groupby(by="cluster_rep").count().sort_values(by="PDB", ascending=False)
counts.head(20)

             PDB
cluster_rep
4ipz          19
3avn          12
5esq           9
4k8y           6
7pgc           6
4mq9           5
6cn8           5
7s5g           5
7pfq           5
6obr           4
8r7t           4
3odi           4
8be7           4
2nym           3
6o6x           3
6kdi           3
3wne           3
4i5n           2
4jzu           2
5tyi           2